### PR TITLE
Revert "Make an option to use a sufficient L2 cache for QCOW2 images"

### PR DESCRIPTION
**Pull request by 20lives**
there is an issue with runnig test images, reverting until figured out.

This reverts commit 31df3a166104f77aa0c65878c73bf8f39729085f.

### CODE REVIEW

**Comment by blochl** [comment]
> there is an issue with runnig test images, reverting until figured out.

Hi,
Can you please tell what the issue is?

**Comment by 20lives** [comment]
Sure, it's probably something very simple.
I tried to run a 'fs-filter' device test which run `prepare_test_image`.
it seems that the `$(set_qcow2_l2_cache `test_image_name 1`)` on it isn't working right at:
``
TEST_STORAGE_PAIR="-drive file=`test_image_name 1`$(set_qcow2_l2_cache `test_image_name 1`),if=none,format=qcow2,id=virtio_scsi${DRIVE_CACHE_OPTION}
``

**Comment by blochl** [comment]
But what's the error?

**Comment by 20lives** [comment]
```
qemu-img: Could not open '/home/hck-ci/Prometheus/VirtHCK/images/ConMon-Win2016x64/2018_06_25_19_11_32/client1_test_image1.qcow2': Could not open '/home/hck-ci/Prometheus/VirtHCK/images/Con$
on-Win2016x64/2018_06_25_19_11_32/client1_test_image1.qcow2': No such file or directory
Creating test image of 30G /home/hck-ci/Prometheus/VirtHCK/images/ConMon-Win2016x64/2018_06_25_19_11_32/client1_test_image1.qcow2...
Formatting '/home/hck-ci/Prometheus/VirtHCK/images/ConMon-Win2016x64/2018_06_25_19_11_32/client1_test_image1.qcow2', fmt=qcow2 size=32212254720 cluster_size=65536 lazy_refcounts=off refcoun$
_bits=16
qemu-system-x86_64: -world_bridge: invalid option
```

**Comment by 20lives** [comment]
btw: `USE_FULL_QCOW2_L2_CACHE` is off

**Comment by blochl** [comment]
Ah, it's clear now. Something simple indeed. :)
(#17)

**Pull request merged**
