### PR TITLE
client: mask last nibble of MAC address differ between test and support

### PR DESCRIPTION
**Pull request by ybendito**
At least RSC test of WLK (8.1) during the test suppresses
address randomisation and only last nibble of MAC is taken
in account when calculating automatic IP address, i.e it
is always 169.254.1.<last_byte_of_MAC>. As a result both
test and support adapter have the same IP address and the
test can't execute. It looks like there is no case when
this change shall break something.

Signed-off-by: Yuri Benditovich <yuri.benditovich@daynix.com>

### CODE REVIEW

**Comment by YanVugenfirer** [comment]
Lior,

Please take a look. Doesn’t it affect guest setup scripts, AutoHCK or something else?

**Comment by 20lives** [comment]
It is breaking the setup script, but this should be easy to overcome on the script side.

**Comment by ybendito** [comment]
@20lives So we're waiting for AutoHCK fix?

**Comment by 20lives** [comment]
I will take back what I wrote before, this change does not affect the script nor any existing image.
This commit can be merged.

**Comment by YanVugenfirer** [comment]
Please resend

**Pull request closed without merging**
