### PR TITLE
4 digit unique ID MAC creation bug fix

### PR DESCRIPTION
**Pull request by bish22ah**
Signed-off-by: Bishara AbuHattoum <bishara@daynix.com>

### CODE REVIEW

**Review by sameehj — CHANGES_REQUESTED** [review]
Please provide a proper commit message!

Where the "UID_FIRST" and "UID_SECOND" are defined?

You are making another change to uuid and not to mac only, this change should go into separate commit.

**Comment by bish22ah** [comment]
"UID_FIRST" and "UID_SECOND" are already defined in hck_aux.sh, i just used them.
i will commit the uuid change separately.

**Review by sameehj — CHANGES_REQUESTED** [review]
You didn't change the commit message, please change it to something more informative like: 
VirtHCK: Use 4 digit unique id for mac address generation

**Comment by bish22ah** [comment]
The 4 digits are already in use, I didnt add it, so this commit message is irrelevant.

**Comment by sameehj** [comment]
Pushed, Thanks =)

**Pull request merged**
